### ISSUE TITLE
User's passwords shouldn't be sent in emails

### ISSUE THREAD

**Issue by taoeffect** [mailpile/HoiPoi#1]
There should be a way for users to identify themselves in the system (this can be done with passwords, OpenID, or other authentication mechanisms).

Emails sent to users should not have in them: `Password: ********` as that's considered poor practice and reflects poorly on the organization (regardless of whether that is actually an "access token" or w/e).

Here's now the welcome email currently looks:

![screen_shot_2015-05-18_at_3 22 07_pm](https://cloud.githubusercontent.com/assets/138706/7692069/0a97f62c-fd75-11e4-8433-0d17877f1150.jpg)

**Comment by taoeffect** [comment]
Obviously if you are storing passwords in plain text that's a serious problem as well (but from our twitter convo it sounds like you're not).

**Comment by BjarniRunar** [comment]
You have not demonstrated any security risks, you have just stated that you don't like this.

Please explain what the risk is and how you propose to invite users to the system when all we know about them is an e-mail address.

**Comment by taoeffect** [comment]
How are you authenticating users?

**Comment by BjarniRunar** [comment]
Dude, until you demonstrate a problem, why should I spend time walking you through things? I have a LOT of more important work to do. It's not a lot of code. If you care, read it.

And quite frankly, I'm not keen to give in to bullies - which is exactly what you were when you threatened public shaming for a security vulnerability which the system demonstrably does not have. Or do you not even understand the security flaws you are accusing us of? Let me spell it out for you. Passwords in e-mail are a problem, because they are usually a sign that the sender kept a password in plain text. Keeping passwords in plain text is bad, because password databases get stolen and then one compromised site can lead to other targets of value falling as well, because users reuse passwords.

None of this applies to password-reset style messages where a random password is generated, which is what we did here. And given that we only have an e-mail address with which to contact people, sending a random token is THE industry standard way of doing this kind of thing. None of the other alternatives you mention will work, and even if they did, things like OpenID leak information about the user's interaction with our site, to a third party. That is not obviously better.

The only personal information currently stored by our system, is the user's name - and if someone could intercept the user's e-mail to steal the token, they knew that already. There is no security risk here, not because we blindly follow dogmatic rules, but because we actually thought about how to avoid putting users at risk and chose not to keep user data on the server at all.

But, in spite of all that, because we recognize that the HoiPoi will grow and evolve and eventually allow users to change their passwords (they can't at the moment), and others might use it less carefully than Mailpile has, HoiPoi uses PDKDF2 when processing the authentication token. So again, best practices given the libraries we had available to us.

So you can keep making demands and I'll just keep ignoring you. Or you can read the code and contribute patches to make things better, or bug reports if you actually find flaws. So far, you have neither demonstrated a flaw, nor demonstrated even basic understanding of the security issues you claim to care about. All you have demonstrated is a willingness to jump to conclusions, make threats, make demands and waste my time.

This kind of shit does not improve Internet security, it just contributes to making the community toxic and off-putting. Sorry if this is harsh, but if you're going to dish out the abuse and then refuse to back down when corrected, this is what you get.

(Back-story for those finding this issue without context: This started with a threat on Twitter to post the Mailpile community page to a public shaming database of sites storing user passwords unencrypted. I don't like being threatened for no good reason.)

**Comment by taoeffect** [comment]
Only one being toxic here is you buddy.

Could you kindly refund my donation?

**Comment by BjarniRunar** [comment]
If the fact that I refuse to be bullied, means you no longer believe in the work I'm doing... well, not much I can say to that.

I'll refund you out of my own pocket, it would be wrong for the project's limited finances to suffer because I don't hesitate to yell at people I feel deserve it.

I'll e-mail you.

**Comment by taoeffect** [comment]
I have no interest in bullying anyone. Nor have I interest in financially supporting a project that treats its supporters and those who bring concerns to it the way you do.
